Allow checking for functions anywhere in the stack
uber-go/goleak pull request #80
Opened 2022-09-05 13:26 UTC by thomshutt

2022-10-11 10:09 UTC, thomshutt commented
👋 This has been open for a while now, if there's anything you'd like me to change then let me know. Similarly if it's not functionality that you want to add then I can close the PR.

2023-02-03 07:50 UTC, pohly commented
This would be useful for [a more precise suppression of a goroutine in Kubernetes](https://github.com/kubernetes/kubernetes/pull/115456#discussion_r1094960760) which is currently reported as being in `time.Sleep`.

2023-04-03 21:16 UTC, abhinav approved these changes

2023-04-03 22:44 UTC, prashantv requested changes
I'm +1 on adding this functionality, but don't think it should be done using `strings.Contains` on the raw stack.

I'd prefer if we updated the parser to understand the function names specifically, and allow matching on the function name only.

2023-04-05 05:06 UTC, prashantv reviewed
Thanks for updating the parsing logic, left a couple of comments on the parser + tests.

2023-04-05 05:06 UTC, prashantv commented on internal/stack/stacks.go
>  		}
this looks like it's trying to parse every line, should we instead parse only the lines known to be functions?

I think the format is:
```
<function>
<tab><file:line>
<function>
<tab><file:line>
...
```

2023-04-05 05:06 UTC, prashantv commented on internal/stack/stacks.go
> +	}
since it's not part of the stack, may be better to skip parsing these till it's required

2023-06-23 18:25 UTC, brandur commented
@thomshutt Any chance you're still around to address those code changes? I was just about to file an issue over lacking this functionality before I found this PR because I needed it too.

2023-10-23 17:24 UTC, abhinav commented
Superseded by #113 
Closing

2023-10-23 17:24 UTC, closed without merging